name: golangci-lint
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
        - name: Set up Go 1.x
          uses: actions/setup-go@v2
          with:
            go-version: ^1.14
          id: go
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2
        - name: Get dependencies
          run: |
           go mod download
        - name: Build
          run: go build -v ./...
        - name: Test
          run: go test -v ./...
        - name: Coverage
          run: go test -v -covermode=count -coverprofile=coverage.out
        - name: Convert coverage to lcov
          uses: jandelgado/gcov2lcov-action@v1.0.0
          with:
              infile: coverage.out
              outfile: coverage.lcov
        - name: Coveralls
          uses: coverallsapp/github-action@v1.0.1
          with:
              github-token: ${{ secrets.github_token }}
              path-to-lcov: coverage.lcov 
          
    
    golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v2
          with:
            version: v1.29
            # see https://golangci-lint.run/usage/linters/
            args: --enable misspell,gofmt,golint,goimports